# Generated by Django 4.2.7 on 2025-06-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='상태 메시지'),
        ),
    ]
